version: '3'

services:
    postgres:
        container_name: nest-rb
        image: postgres
        ports:
            - 5432:5432
        env_file:
            - .env
        environment:
            - POSTGRES_USER=${POSTGRES_USER}
            - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
            - POSTGRES_DB=${POSTGRES_DB}
            - PGDATA=${PGDATA}
        volumes:
            - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
  node_modules:
